#file write operation
f=open("fwrite.txt","w")
f.write("My name is Ms.Tejaswita Sitaram Wakhure\n")
f.write("I have completed my M.E degree from Pune University\n")
f.write("I am serching for a job in Machine Learning Sector\n")
print("Name of file is: ",f.name)
print("Mode of file is: ",f.mode)
print("File is closed or not: ",f.closed)
print("File is Readable: ",f.readable())
print("File is writable: ",f.writable())
f.close()
print("File is closed or not: ",f.closed)
f=open("fwrite.txt","r")
d=f.read()
print(d)
f.close()
